stages:
- name: compile
  steps:
  - runScriptConfig:
      image: sangrei/maven:3.6.0-jdk-8-alpine
      shellScript: mvn clean package
- name: biuld
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: sangrei/gateway:v0.1
      pushRemote: true
      registry: index.docker.io
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
