apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  namespace: basic-service
  labels:
    app: basic-service
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway
        track: master
    spec:
      containers:
      - name: gateway
        image: sangrei/gateway:v0.1
        imagePullPolicy: Always
        env:
        - name: eureka.serviceUrl
          value: http://192.168.72.3:9011/eureka/
        - name: zipkin.base-url
          value: http://192.168.72.3:9075/
        ports:
        - containerPort: 80
          hostPort: 9015
