apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway
        track: master
    spec:
      containers:
      - name: product
        image: sangrei/gateway:v0.1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9013